api_url: "http://crafty:8111"
username: "admin"
password: "password"
timeout: "2m"
auto_shutdown: true

addresses:
  - external_port: "25565"
    external_ip: "crafty"
    internal_ip: "localhost"
    internal_port: "25565"
    protocol: "tcp"
